environments:
  dev:
    values:
      - environments/dev.yaml
  stage:
    values:
      - environments/stage.yaml

releases:
  - name: my-app
    chart: ./charts/my-app
    namespace: default
    values:
      - ./charts/my-app/values.yaml
